package domain

type record struct {
	server    string
	available string
}

/*
newRecord func
*/
func newRecord(server, available string) *record {
	return &record{server: server, available: available}
}

// TLDs list
var TLDs = map[string]*record{
	"ac":     newRecord("whois.nic.ac", "NOT FOUND"),
	"ae":     newRecord("whois.aeda.net.ae", "No Data Found"),
	"aero":   newRecord("whois.aero", "NOT FOUND"),
	"af":     newRecord("whois.nic.af", "No Object Found"),
	"ag":     newRecord("whois.nic.ag", "NOT FOUND"),
	"am":     newRecord("whois.amnic.net", "No match"),
	"as":     newRecord("whois.nic.as", "NOT FOUND"),
	"asia":   newRecord("whois.nic.asia", "NOT FOUND"),
	"at":     newRecord("whois.nic.at", "nothing found"),
	"au":     newRecord("whois.aunic.net", "NOT FOUND"),
	"ax":     newRecord("whois.ax", "Domain not found"),
	"be":     newRecord("whois.dns.be", "Status: AVAILABLE"),
	"bg":     newRecord("whois.register.bg", "registration status: available"),
	"bi":     newRecord("whois.nic.bi", "Domain Status: No Object Found"),
	"biz":    newRecord("whois.neulevel.biz", "No Data Found"),
	"bj":     newRecord("www.nic.bj", "Domain Status: No Object Found"),
	"br":     newRecord("whois.nic.br", "No match for"),
	"by":     newRecord("whois.cctld.by", "Object does not exist"),
	"ca":     newRecord("whois.cira.ca", "Not found: "),
	"cat":    newRecord("whois.cat", "The queried object does not exist: no matching objects found"),
	"cc":     newRecord("whois.nic.cc", "No match for"),
	"cl":     newRecord("whois.nic.cl", ": no entries found."),
	"cn":     newRecord("whois.cnnic.net.cn", "No matching record."),
	"co":     newRecord("whois.nic.co", "No Data Found"),
	"com":    newRecord("whois.verisign-grs.com", "No match for"),
	"coop":   newRecord("whois.nic.coop", "The queried object does not exist:"),
	"cx":     newRecord("whois.nic.cx", "Domain Status: No Object Found"),
	"de":     newRecord("whois.denic.de", "Status: free"),
	"dk":     newRecord("whois.dk-hostmaster.dk", "No entries found for the selected source."),
	"dm":     newRecord("whois.nic.cx", "The queried object does not exist: "),
	"dz":     newRecord("whois.nic.dz", "NO OBJECT FOUND!"),
	"edu":    newRecord("whois.educause.net", "NO MATCH:"),
	"ee":     newRecord("whois.tld.ee", "Domain not found"),
	"eu":     newRecord("whois.eu", "Status: AVAILABLE"),
	"fi":     newRecord("whois.ficora.fi", "Domain not found"),
	"fo":     newRecord("whois.nic.fo", "The queried object does not exist:"),
	"fr":     newRecord("whois.nic.fr", "No entries found in the AFNIC Database"),
	"gb.com": newRecord("whois.centralnic.com", "No match for domain"),
	"qc.com": newRecord("whois.centralnic.com", "No match for domain"),
	"ge":     newRecord("whois.ripe.net", "No match for"),
	"gl":     newRecord("whois.nic.gl", "Domain Status: No Object Found"),
	"gov":    newRecord("whois.nic.gov", "No match for"),
	"gs":     newRecord("whois.nic.gs", "Domain Status: No Object Found"),
	"hk":     newRecord("whois.hknic.net.hk", "The domain has not been registered."),
	"hr":     newRecord("whois.dns.hr", "No entries found"),
	"hu":     newRecord("whois.nic.hu", "No match"),
	"hu.com": newRecord("whois.centralnic.com", "No match for domain"),
	"id":     newRecord("whois.pandi.or.id", "DOMAIN NOT FOUND"),
	"ie":     newRecord("whois.domainregistry.ie", "Not Registered - The domain you have requested"),
	"in":     newRecord("whois.inregistry.net", "No Data Found"),
	"info":   newRecord("whois.afilias.info", "NOT FOUND"),
	"int":    newRecord("whois.isi.edu", "NOT FOUND"),
	"io":     newRecord("whois.nic.io", "NOT FOUND"),
	"ir":     newRecord("whois.nic.ir", "no entries found"),
	"is":     newRecord("whois.isnic.is", "No entries found for query"),
	"je":     newRecord("whois.je", "NOT FOUND"),
	"jobs":   newRecord("jobswhois.verisign-grs.com", "No match for"),
	"kg":     newRecord("whois.domain.kg", "Data not found. This domain is available for registration."),
	"kr":     newRecord("whois.nic.or.kr", "The requested domain was not found in the Registry or Registrar’s WHOIS Server"),
	"la":     newRecord("whois2.afilias-grs.net", "The queried object does not exist:"),
	"lu":     newRecord("whois.restena.lu", "No such domain"),
	"lv":     newRecord("whois.nic.lv", "Status: free"),
	"ly":     newRecord("whois.lydomains.com", "Not found"),
	"ma":     newRecord("whois.iam.net.ma", "Domain Status: No Object Found"),
	"md":     newRecord("whois.nic.md", "No match for"),
	"me":     newRecord("whois.nic.me", "NOT FOUND"),
	"mk":     newRecord("whois.ripe.net", "No entries found"),
	"mobi":   newRecord("whois.dotmobiregistry.net", "NOT FOUND"),
	"ms":     newRecord("whois.nic.ms", "Domain Status: No Object Found"),
	"mu":     newRecord("whois.nic.mu", "Domain Status: No Object Found"),
	"mx":     newRecord("whois.nic.mx", "No_Se_Encontro_El_Objeto/Object_Not_Found"),
	"name":   newRecord("whois.nic.name", "No match for"),
	"net":    newRecord("whois.verisign-grs.com", "No match for domain"),
	"nf":     newRecord("whois.nic.cx", "Domain Status: No Object Found"),
	"ng":     newRecord("whois.nic.net.ng", "Domain Status: No Object Found"),
	"no":     newRecord("whois.norid.no", "No match"),
	"no.com": newRecord("whois.centralnic.com", "No match for domain"),
	"nu":     newRecord("whois.nic.nu", "not found."),
	"nz":     newRecord("whois.srs.net.nz", "query_status: 220 Available"),
	"org":    newRecord("whois.pir.org", "NOT FOUND"),
	"pl":     newRecord("whois.dns.pl", "No information available about domain name"),
	"pr":     newRecord("whois.nic.pr", "NOT FOUND"),
	"pro":    newRecord("whois.registrypro.pro", "NOT FOUND"),
	"pw":     newRecord("whois.nic.pw", "The queried object does not exist: DOMAIN NOT FOUND"),
	"ro":     newRecord("whois.rotld.ro", "No entries found for the selected source(s)."),
	"ru":     newRecord("whois.tcinet.ru", "No entries found for the selected source(s)."),
	"sa.com": newRecord("whois.centralnic.com", "No match for domain "),
	"sc":     newRecord("whois2.afilias-grs.net", "NOT FOUND"),
	"se":     newRecord("whois.nic-se.se", "not found."),
	"se.com": newRecord("whois.centralnic.com", "No match for domain "),
	"sg":     newRecord("whois.nic.net.sg", "Domain Not Found"),
	"sh":     newRecord("whois.nic.sh", "NOT FOUND"),
	"si":     newRecord("whois.arnes.si", "No entries found for the selected source(s)."),
	"sk":     newRecord("whois.sk-nic.sk", "Domain not found."),
	"sm":     newRecord("whois.nic.sm", "No entries found."),
	"st":     newRecord("whois.nic.st", "No entries found for domain"),
	"so":     newRecord("whois.nic.so", "Domain Status: No Object Found"),
	"su":     newRecord("whois.tcinet.ru", "No entries found for the selected source(s)."),
	"tc":     newRecord("whois.adamsnames.tc", "Domain Status: No Object Found"),
	"tel":    newRecord("whois.nic.tel", "No Data Found"),
	"tf":     newRecord("whois.nic.tf", "No entries found in the AFNIC Database."),
	"th":     newRecord("whois.thnic.net", "No match for"),
	"tk":     newRecord("whois.nic.tk", "Invalid query or domain name not known in Dot TK Domain Registry"),
	"tl":     newRecord("whois.domains.tl", "Domain Status: No Object Found"),
	"tm":     newRecord("whois.nic.tm", "is available for purchase"),
	"tn":     newRecord("whois.ati.tn", "NO OBJECT FOUND!"),
	"travel": newRecord("whois.nic.travel", "No Data Found"),
	"tw":     newRecord("whois.twnic.net.tw", "No Found"),
	"tv":     newRecord("whois.nic.tv", "No match for"),
	"tz":     newRecord("whois.tznic.or.tz", "no entries found"),
	"ua":     newRecord("whois.ua", "No entries found for"),
	"uk":     newRecord("whois.nic.uk", "This domain name has not been registered."),
	"us":     newRecord("whois.nic.us", "No Data Found"),
	"uy.com": newRecord("whois.centralnic.com", "No match for domain"),
	"uz":     newRecord("whois.cctld.uz", "not found in database"),
	"vc":     newRecord("whois2.afilias-grs.net", "NOT FOUND"),
	"ve":     newRecord("whois.nic.ve", "No entries found"),
	"vg":     newRecord("whois.adamsnames.tc", "The queried object does not exist: DOMAIN NOT FOUND"),
	"ws":     newRecord("whois.website.ws", "The queried object does not exist:"),
	"xxx":    newRecord("whois.nic.xxx", "is available for registration"),
	"yu":     newRecord("whois.ripe.net", "this server does not have"),
	"za.com": newRecord("whois.centralnic.com", "No match for domain"),
	// "uk.com": newRecord("whois.centralnic.com", "No match for domain"),
	// "uk.net": newRecord("whois.centralnic.com", "No match for domain"),
	// "us.com": newRecord("whois.centralnic.com", "No match for domain"),
	// "cn.com": newRecord("whois.centralnic.com", "No match for domain"),
	// "se.net": newRecord("whois.centralnic.com", "No match for domain "),
	// "gb.net": newRecord("whois.centralnic.com", "No match for domain"),
	// "eu.com": newRecord("whois.centralnic.com", "No match for domain"),
	// "br.com": newRecord("whois.centralnic.com", "No match for domain "),
	// "nl":newRecord("whois.domain-registry.nl", "No Data Found"),
	// "lt":newRecord("whois.domreg.lt", "No Data Found"),
	// "cz":newRecord("whois.nic.cz", "No Data Found"),
	// "it":newRecord("whois.nic.it", "No Data Found"),
}
